[project]
name = "odd-number-hacking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ethan Hadley", email = "ekhadley@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.70.0",
    "transformer-lens>=3.8.0",
    "transformers>=5.16.1",
]
